In [1]:
import numpy as np

In [11]:
def predict(X):
    n = X.shape[0] # shape (n, n)
    Y = np.copy(X)

    for i in range(1,n-1):
        for j in range(1,n-1):
            sum = np.sum(X[i-1:i+2, j-1:j+2])
            if X[i,j] == 1:
                if (sum-1)<2 or (sum-1)>3: 
                    Y[i,j] = 0
            else:
                if sum==3:
                    Y[i,j] = 1
    
    return Y

In [18]:
X = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0]
])


In [19]:
for i in range(10):
    X = predict(X)
    print(X)
    print('')

[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

