In [2]:
import cv2
# print(cv2.__version__)
import numpy as np

## 1

In [43]:
img = cv2.imread('img resize.png')

show anh mau

In [13]:
# w = int(img.shape[1]/5)
# h = int(img.shape[0]/5)
# dim = (w, h)
  
# # resize image
# img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
# print('Resized Dimensions : ',img.shape)

cv2.imshow("Resized image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

convert to gray and show img

In [31]:
r = img[:,:,0]
g = img[:,:,1]
b = img[:,:,2]

gray = (0.299*r + 0.587*g + 0.114*b).astype(np.uint8)

cv2.imshow('gray', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', img_gray)
cv2.waitKey()
cv2.destroyAllWindows()

resize

In [20]:
w = int(img.shape[1]/2)
h = int(img.shape[0]/2)
dim = (w, h)

# resize image
img_resize = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
print('Resized Dimensions : ',img_resize.shape)

cv2.imshow("Resized image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Resized Dimensions :  (400, 228, 3)


rotate

In [9]:
# rotate = np
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

rotate = gray[:,::-1]
rotate = rotate.T
# rotate = img[::-1,:]
# rotate = img[:,:,::-1]
cv2.imshow("rotate", rotate)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [10]:
rotate = gray[::-1,:]
rotate = rotate.T
cv2.imshow("rotate", rotate)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [13]:
rotate = img[::-1,:]
cv2.imshow("rotate", rotate)
cv2.waitKey(0)
cv2.destroyAllWindows()
rotate = img[:,::-1]
cv2.imshow("rotate", rotate)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [15]:
(rows, cols) = img.shape[:2]

# getRotationMatrix2D creates a matrix needed for transformation.
# We want matrix for rotation w.r.t center to 45 degree without scaling.
M = cv2.getRotationMatrix2D((cols / 2, rows / 2), 60, 1)
res = cv2.warpAffine(img, M, (cols, rows))
cv2.imshow("rotate", res)
cv2.waitKey(0)
cv2.destroyAllWindows() 

threshold

In [40]:
thresh = np.copy(img_gray)
threshold = 180
thresh[thresh>threshold] = 255
thresh[thresh<=threshold] = 0
cv2.imshow("thresh", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
ret, thresh1 = cv2.threshold(img_gray, 120, 255, cv2.THRESH_BINARY)
ret, thresh2 = cv2.threshold(img_gray, 120, 255, cv2.THRESH_BINARY_INV)
ret, thresh3 = cv2.threshold(img_gray, 120, 255, cv2.THRESH_TRUNC)
ret, thresh4 = cv2.threshold(img_gray, 120, 255, cv2.THRESH_TOZERO)
ret, thresh5 = cv2.threshold(img_gray, 120, 255, cv2.THRESH_TOZERO_INV)
cv2.imshow('Binary Threshold', thresh1)
cv2.waitKey(0)
cv2.imshow('Binary Threshold Inverted', thresh2)
cv2.waitKey(0)
cv2.imshow('Truncated Threshold', thresh3)
cv2.waitKey(0)
cv2.imshow('Set to 0', thresh4)
cv2.waitKey(0)
cv2.imshow('Set to 0 Inverted', thresh5)
cv2.waitKey(0)
cv2.destroyAllWindows()

line, circle detect

In [44]:
edges = cv2.Canny(img_gray, 100, 200)

cv2.imshow('canny', edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
# Apply HoughLinesP method to
# to directly obtain line end points
lines_list =[]
lines = cv2.HoughLinesP(
            edges, # Input edge image
            1, # Distance resolution in pixels
            np.pi/180, # Angle resolution in radians
            threshold=100, # Min number of votes for valid line
            minLineLength=5, # Min allowed length of line
            maxLineGap=10 # Max allowed gap between line for joining them
            )

img_line = np.copy(img)
# Iterate over points
for points in lines:
      # Extracted points nested in the list
    x1,y1,x2,y2=points[0]
    # Draw the lines joing the points
    # On the original image
    cv2.line(img_line,(x1,y1),(x2,y2),(0,0,255),2)
    # Maintain a simples lookup list for points
    lines_list.append([(x1,y1),(x2,y2)])
    
cv2.imshow('line', img_line)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [64]:
# Blur using 3 * 3 kernel.
gray_blurred = cv2.blur(img_gray, (3, 3))

# Apply Hough transform on the blurred image.
detected_circles = cv2.HoughCircles(gray_blurred,
                                    cv2.HOUGH_GRADIENT, 1, 20, param1=50,
                                    param2=30, minRadius=1, maxRadius=40)

img_circle = np.copy(img)
# Draw circles that are detected.
if detected_circles is not None:

    # Convert the circle parameters a, b and r to integers.
    detected_circles = np.uint16(np.around(detected_circles))

    for pt in detected_circles[0, :]:
        a, b, r = pt[0], pt[1], pt[2]

        # Draw the circumference of the circle.
        cv2.circle(img_circle, (a, b), r, (0, 0, 255), 2)

        # Draw a small circle (of radius 1) to show the center.
        cv2.circle(img_circle, (a, b), 1, (0, 0, 255), 3)
        cv2.imshow("Detected Circle", img_circle)
        cv2.waitKey(0)


## 2

identity

In [65]:
# Apply identity kernel
# In an Identity Kernel matrix the value of the middle element is 1
# The values of all the other elements are 0
id_kernel = np.array([[0, 0, 0],
                    [0, 1, 0],
                    [0, 0, 0]])
  
# Filtered image is obtained using the variable flt_img
# cv2.fliter2D() is the function used
# src is the source of image(here, img)
# ddepth is destination depth. -1 will mean output image will have same depth as input image
# kernel is used for specifying the kernel operation (here, id_kernel)
flt_img = cv2.filter2D(src=img, ddepth=-1, kernel=id_kernel)
  
# Display the filtered image using cv2.imshow() function
# Here, output image is same as input image since we are using identity kernel
cv2.imshow('Identity', flt_img)

# cv2.waitkey(delay) function holds the screen till any key is pressed by the user
# It pauses the screen for delay milliseconds if the delay is a positive value
# It pauses the screen for a key event infinitely if the delay is 0 or negative
cv2.waitKey(0)
  
# cv2.destroyAllWindows() function deletes all the GUI windows from memory
cv2.destroyAllWindows()

box blur

In [66]:
# Kernel for box blur filter
# It is a unity matrix which is divided by 9
box_blur_ker = np.array([[0.1111111, 0.1111111, 0.1111111],
                         [0.1111111, 0.1111111, 0.1111111],
                         [0.1111111, 0.1111111, 0.1111111]])

# Applying Box Blur effect
# Using the cv2.filter2D() function
# src is the source of image(here, img)
# ddepth is destination depth. -1 will mean output image will have same depth as input image
# kernel is used for specifying the kernel operation (here, box_blur_ker)
Box_blur = cv2.filter2D(src=img, ddepth=-1, kernel=box_blur_ker)
cv2.imshow('blur', Box_blur)
cv2.waitKey()
cv2.destroyAllWindows()

sharpen

In [48]:
# Apply kernel for sharpening
sharp_kernel = np.array([[0, -1, 0],
                         [-1, 5, -1],
                         [0, -1, 0]])

# Sharpeneded image is obtained using the variable sharp_img
# cv2.fliter2D() is the function used
# src is the source of image(here, img)
# ddepth is destination depth. -1 will mean output image will have same depth as input image
# kernel is used for specifying the kernel operation (here, sharp_kernel)
sharp_img = cv2.filter2D(src=img, ddepth=-1, kernel=sharp_kernel)
cv2.imshow('sharpen', sharp_img)
cv2.waitKey()
cv2.destroyAllWindows()

edge detection

In [49]:
e1 = np.array([[0, 1, 0],
               [1, -4, 1],
               [0, 1, 0]])
e2 = np.array([[1, 0, -1],
               [0, 0, 0],
               [-1, 0, 1]])
e3 = np.array([[-1, -1, -1],
               [-1, 8, -1],
               [-1, -1, -1]])
edge_kernel = [e1, e2, e3]
for e in edge_kernel:
    edge = cv2.filter2D(src=img, ddepth=-1, kernel=e)
    cv2.imshow('edge', edge)
    cv2.waitKey()

cv2.destroyAllWindows()


## 3

In [35]:
def convolution(img, kernel, p=1, s=1):
    (m, n) = img.shape
    k = kernel.shape[0]
    pad_k = int((k-1)/2)
    m_Y = int((m-k+2*p)/s + 1)
    n_Y = int((n-k+2*p)/s + 1)
    # print(m_Y, n_Y)

    Y = np.zeros((m_Y, n_Y))
    pad_m = np.zeros((m, p))
    X = np.concatenate((pad_m, img, pad_m), axis=1)
    pad_n = np.zeros((p, X.shape[1]))
    X = np.concatenate((pad_n, X, pad_n), axis=0)

    i = j = 0
    c1 = c2 = 0
    while(c1+pad_k+2 <= m+2*p):
        
        while(c2+pad_k+2 <= n+2*p):
            A = X[c1-pad_k+1:c1+pad_k+2, c2-pad_k+1:c2+pad_k+2]
            Y[i, j] = np.sum((A*kernel))
            j += 1
            # print(c1+1, c2+1)
            c2 += s

        c2=0
        j=0
        c1 += s
        i += 1

    return (X, Y)

In [53]:
X = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])
blur_kernel = np.array([[1, 1, 1],
                        [1, 1, 1],
                        [1, 1, 1]])
# kernel = np.copy(X)
(X_res, Y) = convolution(X, blur_kernel,3,3)
print(X_res)
print(Y)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [51]:
e1 = np.array([[0, 1, 0],
               [1, -4, 1],
               [0, 1, 0]])
e2 = np.array([[1, 0, -1],
               [0, 0, 0],
               [-1, 0, 1]])
e3 = np.array([[-1, -1, -1],
               [-1, 8, -1],
               [-1, -1, -1]])
edge_kernel = [e1, e2, e3]
for e in edge_kernel:
    (X_res, Y) = convolution(img_gray, e)
    cv2.imshow('sharp', Y)
    cv2.waitKey()
cv2.destroyAllWindows()
